name: habit_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.2
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: lib/assets/fonts/Comfortaa-Regular.ttf
        - asset: lib/assets/fonts/Comfortaa-Light.ttf
          weight: 100
        - asset: lib/assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Comfortaa-Medium.ttf
          weight: 200
        - asset: lib/assets/fonts/Comfortaa-SemiBold.ttf
          weight: 500
  uses-material-design: true
  assets:
    - lib/assets/images/
